security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: INFO
      
spring:
  sleuth:
    sampler:
      percentage: 1.0 #100%
  zipkin:
    base-url: ${ZIPKIN_SERVER_URI:http://localhost:9411}
#spring:
#  rabbitmq:
#    addresses: ${vcap.services.cloud-bus.credentials.http_api_uris:http://localhost:5672}
